//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquavision.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildCartItem
    {
        public int BuildCartItemId { get; set; }
        public int BuildCartId { get; set; }
        public int ProductOptionId { get; set; }
    
        public virtual BuildCart BuildCart { get; set; }
        public virtual ProductOption ProductOption { get; set; }
    }
}
