//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquavisionConfigurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDesign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDesign()
        {
            this.CustomerDesignSpecs = new HashSet<CustomerDesignSpec>();
        }
    
        public int Id { get; set; }
        public int Customer { get; set; }
        public int Product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDesignSpec> CustomerDesignSpecs { get; set; }
    }
}
